# run on pull requests
on:
  pull_request:
    branches:
      - main
      - master

name: build
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn
      - run: yarn compile
